### ISSUE TITLE
Thanks, and some requests: Expressions, shapekeys

### ISSUE THREAD

**Issue by Vidyut** [DreamSpoon/AMH2B#2]
I tried out the addon and it is very useful and fills some of the big gaps in making MH/MPFB2 work well in Blender. Have you considered bringing in expressions as shapekeys? For example this pack: http://www.makehumancommunity.org/content/expressions_bonus_pack.html

Also, I don't understand some of the viseme shapes. For eg, what is "etc". Or how to assign "S"

Also, it would be great to have a shapekeys option for the visemes. Many of the models need adjusting for example lid cutting through eye in blinks, etc - and for a newbie, it gets complicated to make the correction.

Is there documentation somewhere?

**Comment by Vidyut** [comment]
FACEPALM. Never mind about the "etc" - it is e, t and c shapes. I thought like etcetra and I was wondering what that meant. I am such an idiot. Maybe name it "cet" or something to idiotproof it from people like me. ROFL.

**Comment by DreamSpoon** [comment]
Thank you Vidyut!
I wanted to do Shapekeys too but found it to be too much work considering they need to be adjusted based on the size of the head, shape of face, etc.
Instead I made a function to allow blending a frame of an action (animation), see 3DView -> AMH2B toolbar -> Armature -> Apply Action Frame.
Use Apply Action Frame, and change the Blend Factor to change how much the action is applied - e.g. to apply the Blink action at 50%, or 75%, etc.
To fix Blink so the lid doesn't cut through the eye:
  Create your human model.
  Import the Blink action with AMH2B -> Animation - Viseme -> Load Actions, then load the Blink preset.
  Create a new action, then enable Auto Keying.
  Use AMH2B -> Armature -> Apply Action Frame with the Blink action, setting Blend Factor to less than 1.0 (set the Blend Factor so that the blink looks correct - no overlapping geometry).
  Rename the action to something like "Fixed Blink", then stash the new blinking action so it is saved.
  Go to AMH2B -> Eye Blink -> Add and set the "Close" Blink Action to the stashed action: "Fixed Blink"
  Then Add Blinks.

Hope this helps!
I need to make a video explanation of this, next thing on my todo list!
